DROP TABLE IF EXISTS ghusers CASCADE;
DROP TABLE IF EXISTS posts;

CREATE TABLE ghusers (
username TEXT NOT NULL PRIMARY KEY,
avatar TEXT NOT NULL,
email TEXT
);

CREATE TABLE posts (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  post VARCHAR(255) NOT NULL,
  username TEXT REFERENCES ghusers(username)
);

